### ISSUE TITLE
Repair by sign

### ISSUE THREAD

**Issue by Kryniowesegryderiusz** [demengc/UltraRepair#4]
It would be awesome to have repair signs, in which i can set separate costs and permission for them :D

**Comment by demengc** [comment]
Repairing a specified players' will be added along with the plugin re-code. Then, you can use CommandButtons:
https://demeng7215.github.io/Website/commandbuttons.html

**Comment by Kryniowesegryderiusz** [comment]
@Demeng7215 but then you need to have permission for repair and im talking about people that to not have permission for command, but have permission for repairing via sign

**Comment by demengc** [comment]
Like I said, you will be allowed to repair other people's items in the next big update. The players whose item is getting repaired doesn't need the permission.
